#SPDX-License-Identifier: MIT-0
---
# defaults file for unifi.controller
unifi_version: latest
unifi_codename: bookworm
unifi_repo_url: https://www.ui.com/downloads/unifi/debian
unifi_gpg_key_url: https://dl.ui.com/unifi/unifi-repo.gpg

mongodb_repo_key_url: https://www.mongodb.org/static/pgp/server-6.0.asc
mongodb_repo_url: "https://repo.mongodb.org/apt/debian"
mongodb_version: "6.0"

enable_tls: false
tls_cert_path: ""
tls_key_path: ""
